/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RadarInfluenciaChatgptRouteImport } from './routes/radar-influencia-chatgpt'
import { Route as ApiPublicRadarInfluenciaRouteImport } from './routes/api/public/radar-influencia'
import { Route as ApiPublicRadarInfluenciaAlertasRouteImport } from './routes/api/public/radar-influencia-alertas'
import { Route as ApiPublicRadarInfluenciaResumoRouteImport } from './routes/api/public/radar-influencia-resumo'
import { Route as ApiPublicHooksNovosPrevistosRouteImport } from './routes/api/public/hooks/novos-previstos'
import { Route as ApiPublicHooksPagamentosPrevistosRouteImport } from './routes/api/public/hooks/pagamentos-previstos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarInfluenciaChatgptRoute = RadarInfluenciaChatgptRouteImport.update({
  id: '/radar-influencia-chatgpt',
  path: '/radar-influencia-chatgpt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRadarInfluenciaRoute =
  ApiPublicRadarInfluenciaRouteImport.update({
    id: '/api/public/radar-influencia',
    path: '/api/public/radar-influencia',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRadarInfluenciaAlertasRoute =
  ApiPublicRadarInfluenciaAlertasRouteImport.update({
    id: '/api/public/radar-influencia-alertas',
    path: '/api/public/radar-influencia-alertas',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRadarInfluenciaResumoRoute =
  ApiPublicRadarInfluenciaResumoRouteImport.update({
    id: '/api/public/radar-influencia-resumo',
    path: '/api/public/radar-influencia-resumo',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksNovosPrevistosRoute =
  ApiPublicHooksNovosPrevistosRouteImport.update({
    id: '/api/public/hooks/novos-previstos',
    path: '/api/public/hooks/novos-previstos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPagamentosPrevistosRoute =
  ApiPublicHooksPagamentosPrevistosRouteImport.update({
    id: '/api/public/hooks/pagamentos-previstos',
    path: '/api/public/hooks/pagamentos-previstos',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/radar-influencia-chatgpt': typeof RadarInfluenciaChatgptRoute
  '/api/public/radar-influencia': typeof ApiPublicRadarInfluenciaRoute
  '/api/public/radar-influencia-alertas': typeof ApiPublicRadarInfluenciaAlertasRoute
  '/api/public/radar-influencia-resumo': typeof ApiPublicRadarInfluenciaResumoRoute
  '/api/public/hooks/novos-previstos': typeof ApiPublicHooksNovosPrevistosRoute
  '/api/public/hooks/pagamentos-previstos': typeof ApiPublicHooksPagamentosPrevistosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/radar-influencia-chatgpt': typeof RadarInfluenciaChatgptRoute
  '/api/public/radar-influencia': typeof ApiPublicRadarInfluenciaRoute
  '/api/public/radar-influencia-alertas': typeof ApiPublicRadarInfluenciaAlertasRoute
  '/api/public/radar-influencia-resumo': typeof ApiPublicRadarInfluenciaResumoRoute
  '/api/public/hooks/novos-previstos': typeof ApiPublicHooksNovosPrevistosRoute
  '/api/public/hooks/pagamentos-previstos': typeof ApiPublicHooksPagamentosPrevistosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/radar-influencia-chatgpt': typeof RadarInfluenciaChatgptRoute
  '/api/public/radar-influencia': typeof ApiPublicRadarInfluenciaRoute
  '/api/public/radar-influencia-alertas': typeof ApiPublicRadarInfluenciaAlertasRoute
  '/api/public/radar-influencia-resumo': typeof ApiPublicRadarInfluenciaResumoRoute
  '/api/public/hooks/novos-previstos': typeof ApiPublicHooksNovosPrevistosRoute
  '/api/public/hooks/pagamentos-previstos': typeof ApiPublicHooksPagamentosPrevistosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/radar-influencia-chatgpt'
    | '/api/public/radar-influencia'
    | '/api/public/radar-influencia-alertas'
    | '/api/public/radar-influencia-resumo'
    | '/api/public/hooks/novos-previstos'
    | '/api/public/hooks/pagamentos-previstos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/radar-influencia-chatgpt'
    | '/api/public/radar-influencia'
    | '/api/public/radar-influencia-alertas'
    | '/api/public/radar-influencia-resumo'
    | '/api/public/hooks/novos-previstos'
    | '/api/public/hooks/pagamentos-previstos'
  id:
    | '__root__'
    | '/'
    | '/radar-influencia-chatgpt'
    | '/api/public/radar-influencia'
    | '/api/public/radar-influencia-alertas'
    | '/api/public/radar-influencia-resumo'
    | '/api/public/hooks/novos-previstos'
    | '/api/public/hooks/pagamentos-previstos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RadarInfluenciaChatgptRoute: typeof RadarInfluenciaChatgptRoute
  ApiPublicRadarInfluenciaRoute: typeof ApiPublicRadarInfluenciaRoute
  ApiPublicRadarInfluenciaAlertasRoute: typeof ApiPublicRadarInfluenciaAlertasRoute
  ApiPublicRadarInfluenciaResumoRoute: typeof ApiPublicRadarInfluenciaResumoRoute
  ApiPublicHooksNovosPrevistosRoute: typeof ApiPublicHooksNovosPrevistosRoute
  ApiPublicHooksPagamentosPrevistosRoute: typeof ApiPublicHooksPagamentosPrevistosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar-influencia-chatgpt': {
      id: '/radar-influencia-chatgpt'
      path: '/radar-influencia-chatgpt'
      fullPath: '/radar-influencia-chatgpt'
      preLoaderRoute: typeof RadarInfluenciaChatgptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/radar-influencia': {
      id: '/api/public/radar-influencia'
      path: '/api/public/radar-influencia'
      fullPath: '/api/public/radar-influencia'
      preLoaderRoute: typeof ApiPublicRadarInfluenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/radar-influencia-alertas': {
      id: '/api/public/radar-influencia-alertas'
      path: '/api/public/radar-influencia-alertas'
      fullPath: '/api/public/radar-influencia-alertas'
      preLoaderRoute: typeof ApiPublicRadarInfluenciaAlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/radar-influencia-resumo': {
      id: '/api/public/radar-influencia-resumo'
      path: '/api/public/radar-influencia-resumo'
      fullPath: '/api/public/radar-influencia-resumo'
      preLoaderRoute: typeof ApiPublicRadarInfluenciaResumoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/novos-previstos': {
      id: '/api/public/hooks/novos-previstos'
      path: '/api/public/hooks/novos-previstos'
      fullPath: '/api/public/hooks/novos-previstos'
      preLoaderRoute: typeof ApiPublicHooksNovosPrevistosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/pagamentos-previstos': {
      id: '/api/public/hooks/pagamentos-previstos'
      path: '/api/public/hooks/pagamentos-previstos'
      fullPath: '/api/public/hooks/pagamentos-previstos'
      preLoaderRoute: typeof ApiPublicHooksPagamentosPrevistosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RadarInfluenciaChatgptRoute: RadarInfluenciaChatgptRoute,
  ApiPublicRadarInfluenciaRoute: ApiPublicRadarInfluenciaRoute,
  ApiPublicRadarInfluenciaAlertasRoute: ApiPublicRadarInfluenciaAlertasRoute,
  ApiPublicRadarInfluenciaResumoRoute: ApiPublicRadarInfluenciaResumoRoute,
  ApiPublicHooksNovosPrevistosRoute: ApiPublicHooksNovosPrevistosRoute,
  ApiPublicHooksPagamentosPrevistosRoute:
    ApiPublicHooksPagamentosPrevistosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
